name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'segnomms/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci.yml'
      - 'repo/setup_apt_fallback.sh'
      - 'repo/quality_gate_checker.sh'
      - 'repo/test_segno_compatibility.py'
      - 'repo/generate_example_qrs.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'segnomms/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci.yml'
      - 'repo/setup_apt_fallback.sh'
      - 'repo/quality_gate_checker.sh'
      - 'repo/test_segno_compatibility.py'
      - 'repo/generate_example_qrs.py'

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Cache UV and Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-python${{ matrix.python-version }}-${{ hashFiles('**/uv.lock', 'pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-python${{ matrix.python-version }}-
          uv-${{ runner.os }}-

    - name: Install dependencies
      run: |
        uv sync
        uv pip install -e .

    - name: Run linting
      run: |
        make test-lint

    - name: Run type checking
      run: |
        make test-typecheck

    - name: Run unit tests
      run: |
        make test-unit

    - name: Run integration tests
      run: |
        make test-integration

    - name: Run structural tests
      run: |
        make test-structural

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  documentation:
    name: Documentation Build
    uses: ./.github/workflows/_docs-build.yml
    with:
      python-version: "3.11"
      fetch-depth: 1
      upload-artifacts: true
      run-link-check: false
      run-coverage-report: false
      dependency-check: true

  compatibility:
    name: Segno Compatibility
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}

    - name: Cache UV and Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ hashFiles('**/uv.lock', 'pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-
          uv-${{ runner.os }}-

    - name: Install dependencies
      run: |
        uv sync
        uv pip install -e .

    - name: Test Segno compatibility
      run: |
        make test-segno-compatibility

  visual-regression:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}

    - name: Cache UV and Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ hashFiles('**/uv.lock', 'pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-
          uv-${{ runner.os }}-

    - name: Cache APT packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: librsvg2-bin
        version: 1.0

    - name: Install system dependencies (fallback)
      run: ./repo/setup_apt_fallback.sh librsvg2-bin

    - name: Install dependencies
      run: |
        uv sync
        uv pip install -e .

    - name: Run visual regression tests
      run: |
        make test-visual

    - name: Upload visual test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: visual-test-results
        path: |
          tests/visual/output/
          tests/visual/diff/

  examples:
    name: Example Generation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}

    - name: Cache UV and Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ hashFiles('**/uv.lock', 'pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-
          uv-${{ runner.os }}-

    - name: Cache APT packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: librsvg2-bin
        version: 1.0

    - name: Install system dependencies (fallback)
      run: ./repo/setup_apt_fallback.sh librsvg2-bin

    - name: Install dependencies
      run: |
        uv sync
        uv pip install -e .

    - name: Generate examples
      run: |
        make test-examples

    - name: Upload example artifacts
      uses: actions/upload-artifact@v4
      with:
        name: generated-examples
        path: examples-generated/

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}

    - name: Cache UV and Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ hashFiles('**/uv.lock', 'pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-python${{ env.PYTHON_VERSION }}-
          uv-${{ runner.os }}-

    - name: Install dependencies
      run: |
        uv sync
        uv pip install -e .

    - name: Run security scan with bandit
      run: |
        uv pip install bandit
        uv run bandit -c .bandit -r segnomms/ -f json -o bandit-report.json

    - name: Summarize security scan
      if: always()
      run: |
        uv run python - <<'PY'
        import json, os, sys

        report_path = 'bandit-report.json'
        summary_path = os.environ.get('GITHUB_STEP_SUMMARY')

        def w(line=''):
            if summary_path:
                with open(summary_path, 'a', encoding='utf-8') as f:
                    f.write(line + '\n')
            else:
                print(line)

        w('## Security Scan (Bandit)')
        if not os.path.exists(report_path):
            w('- No bandit-report.json found')
            sys.exit(0)

        with open(report_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        results = data.get('results', [])
        sev_order = ['HIGH', 'MEDIUM', 'LOW']
        sev_counts = {s: 0 for s in sev_order}
        for r in results:
            s = (r.get('issue_severity') or 'LOW').upper()
            if s in sev_counts:
                sev_counts[s] += 1

        total = len(results)
        w(f'- Findings: {total}')
        w('')
        w('| Severity | Count |')
        w('| --- | ---: |')
        for s in sev_order:
            w(f'| {s} | {sev_counts[s]} |')

        if results:
            # Top findings detail table (max 10 rows)
            w('\n<details><summary>Top findings</summary>\n')
            w('| Severity | Confidence | ID | File | Line | Message |')
            w('| --- | --- | --- | --- | ---: | --- |')
            sev_rank = {'HIGH': 3, 'MEDIUM': 2, 'LOW': 1}
            conf_rank = {'HIGH': 3, 'MEDIUM': 2, 'LOW': 1}

            def esc(text: str) -> str:
                return (text or '').replace('|', '\\|').replace('\n', ' ')

            top = sorted(
                results,
                key=lambda r: (
                    -sev_rank.get((r.get('issue_severity') or 'LOW').upper(), 0),
                    -conf_rank.get((r.get('issue_confidence') or 'LOW').upper(), 0),
                ),
            )[:10]

            for r in top:
                w(
                    f"| {r.get('issue_severity')} | {r.get('issue_confidence')} | {r.get('test_id')} | "
                    f"{esc(r.get('filename'))} | {r.get('line_number')} | {esc(r.get('issue_text'))} |"
                )
            w('\n</details>')
        PY

    - name: Upload security scan results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: bandit-report.json

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [test, documentation, compatibility, visual-regression, examples, security]
    if: always()
    steps:
    - uses: actions/checkout@v4

    - name: Evaluate quality gate
      run: |
        ./repo/quality_gate_checker.sh \
          --test="${{ needs.test.result }}" \
          --docs="${{ needs.documentation.result }}" \
          --compatibility="${{ needs.compatibility.result }}" \
          --visual="${{ needs.visual-regression.result }}" \
          --examples="${{ needs.examples.result }}" \
          --security="${{ needs.security.result }}" \
          --verbose
